export const skills = [
    {
        id: 1,
        title: "Front-end web development",
        logo: "skillCard-i fa-brands fa-react",
        desc: "Use React and CSS to create interactive and beautifully designed websites based on stakeholder requirements and needs",
    },
    {
        id: 2,
        title: "Back-end web development",
        logo: "fa-brands fa-node",
        desc: "Use Node-js and MongoDB to store information and create CRUD functionality for the user, while focusing on the user's information privacy and security",
    },
    {
        id: 3,
        title: "Python Automation",
        logo: "skillCard-i fa-brands fa-python",
        desc: "Use Python programming to create executables that automate excel reports and enhance efficiency",
    },
    {
        id: 4,
        title: "MS Office Excel Proficiency",
        logo: "fa-solid fa-chart-line",
        desc: "Created various tools and reports for performance tracking, planning and forecasting. Utilize excel formulas, Pivot tables, vba and more",
    },
]

export const projects = [
    {
        id: 6,
        cat: "Web-development",
        title: "Simply",
        status: "incomplete",
        img: "./img/simply.png",
        video: "",
        overview: "Music streaming website where users can post multiple tracks at the same time and create multiple playlists. Uses JWT authentication, password encryption (bcrypt), email OTP verification and other methods to secure user's information.",
        designGoals:[["fa-solid fa-sitemap","Simple Process Flow", "Ability to upload and update multiple tracks with one click makes it very easy to maintain playlists."],["fa-solid fa-shield","Data Security", "Uses JWT authentication, password encryption (bcrypt), email OTP verification and other methods to secure user's information."],["fa-solid fa-desktop","Responsive Design", "Designed to be adaptable to all web platforms."],["fa-solid fa-chart-line","Provide Analytics", "Insight page provides analytics for the user. Administrative user has limited permissions, but it able to easily maintain different account's data."]],
        additionalPic: "../img/simply-add.png",
        tools: ["MERN Stack App", "Axios", "Firebase", "Material-ui", "Redux", "Styled-Components", "Google charts"],
        link: "",
        githubLink: "https://github.com/ajaramillo6/song-proof-app",
    },
    {
        id: 5,
        cat: "Web-development",
        title: "Backpack",
        status: "in-process",
        img: "./img/ex1.jpg",
        video: "https://drive.google.com/file/d/1lxQXSL0XTLOxkqVipisovul8YdeWQGoj/preview",
        overview: "Created a travel blog website which allows registered users to create their own posts from different trips they’ve been on. Each post can include multiple images and links, making easy for the reader to visualize the location(s) and navigate to related pages via the links provided. If the reader prefers reading with a dark background, the 'Dark Mode' option is available. Unregistered users can subscribe to leave comments and likes on different posts.",
        designGoals:[["fa-solid fa-sitemap","Simple Process Flow","Ability to add or delete post sections before uploading final post. Instructions are provided for adding links to different words of the post."],["fa-solid fa-images","Multiple Pictures & Links per Post","Ability to add more than one image per post and add as many links as needed."],["fa-solid fa-desktop","Responsive Design","Designed to be adaptable to all web platforms."], ["fa-solid fa-shield", "Data Security", "Utilizes bcrypt encryption to protect user's password."]],
        additionalPic: "../img/backpack-add.png",
        tools: ["MERN Stack App", "Axios", "Context", "Cloudinary"],
        link: "",
        githubLink: "https://github.com/ajaramillo6/travel",
    },
    {
        id: 4,
        cat: "Web-development",
        title: "enRoll",
        status: "in-process",
        img: "./img/ex5.jpg",
        video: "https://drive.google.com/file/d/1xtaXzjEC3xMboMd-Thz85Mu8hkQRihhn/preview",
        overview: "This food truck business website allows users to purchase food securely using Paypal. Users can select multiple items from the menu and have additional toppings added. There is an admin page where the website owner can modify the menu as needed by creating new items or deleting obsolete ones. The admin page also allows the selection of ‘Featured’ items to have those be promoted on the home page. Each item containing peanuts or spicy sauce contains an icon for the consumer’s knowledge.",
        designGoals:[["fa-solid fa-sitemap","Simple Process Flow", "Ability to order menu items and add sides. Updates provided to customer on the order status."],["fa-solid fa-desktop","Responsive Design","Designed to be adaptable to all web platforms."],["fa-solid fa-shield", "Data Security", "Utilizes bcrypt encryption to protect user's password. Paypal API utilized for secure credit card payments or through the Paypal account."],["fa-solid fa-unlock","Administrative tools","Provided access to control menu information."]],
        additionalPic: "../img/enroll-add.png",
        tools: ["MongoDB", "NextJs", "Axios", "Redux", "Paypal API", "Google Maps API"],
        link: "",
        githubLink: "https://github.com/ajaramillo6/enroll2",
    },
    {
        id: 3,
        cat: "Web-development",
        title: "Simply",
        status: "incomplete",
        img: "./img/simply.png",
        video: "",
        overview: "Music streaming website where users can post multiple tracks at the same time and create multiple playlists. Uses JWT authentication, password encryption (bcrypt), email OTP verification and other methods to secure user's information.",
        designGoals:[["fa-solid fa-sitemap","Simple Process Flow", "Ability to upload and update multiple tracks with one click makes it very easy to maintain playlists."],["fa-solid fa-shield","Data Security", "Uses JWT authentication, password encryption (bcrypt), email OTP verification and other methods to secure user's information."],["fa-solid fa-desktop","Responsive Design", "Designed to be adaptable to all web platforms."],["fa-solid fa-chart-line","Provide Analytics", "Insight page provides analytics for the user. Administrative user has limited permissions, but it able to easily maintain different account's data."]],
        additionalPic: "../img/simply-add.png",
        tools: ["MERN Stack App", "Axios", "Firebase", "Material-ui", "Redux", "Styled-Components", "Google charts"],
        link: "",
        githubLink: "https://github.com/ajaramillo6/song-proof-app",
    },
    {
        id: 2,
        cat: "Web-development",
        title: "Backpack",
        status: "in-process",
        img: "./img/ex1.jpg",
        video: "https://drive.google.com/file/d/1lxQXSL0XTLOxkqVipisovul8YdeWQGoj/preview",
        overview: "Created a travel blog website which allows registered users to create their own posts from different trips they’ve been on. Each post can include multiple images and links, making easy for the reader to visualize the location(s) and navigate to related pages via the links provided. If the reader prefers reading with a dark background, the 'Dark Mode' option is available. Unregistered users can subscribe to leave comments and likes on different posts.",
        designGoals:[["fa-solid fa-sitemap","Simple Process Flow","Ability to add or delete post sections before uploading final post. Instructions are provided for adding links to different words of the post."],["fa-solid fa-images","Multiple Pictures & Links per Post","Ability to add more than one image per post and add as many links as needed."],["fa-solid fa-desktop","Responsive Design","Designed to be adaptable to all web platforms."], ["fa-solid fa-shield", "Data Security", "Utilizes bcrypt encryption to protect user's password."]],
        additionalPic: "../img/backpack-add.png",
        tools: ["MERN Stack App", "Axios", "Context", "Cloudinary"],
        link: "",
        githubLink: "https://github.com/ajaramillo6/travel",
    },
    {
        id: 1,
        cat: "Web-development",
        title: "enRoll",
        status: "in-process",
        img: "./img/ex5.jpg",
        video: "https://drive.google.com/file/d/1xtaXzjEC3xMboMd-Thz85Mu8hkQRihhn/preview",
        overview: "This food truck business website allows users to purchase food securely using Paypal. Users can select multiple items from the menu and have additional toppings added. There is an admin page where the website owner can modify the menu as needed by creating new items or deleting obsolete ones. The admin page also allows the selection of ‘Featured’ items to have those be promoted on the home page. Each item containing peanuts or spicy sauce contains an icon for the consumer’s knowledge.",
        designGoals:[["fa-solid fa-sitemap","Simple Process Flow", "Ability to order menu items and add sides. Updates provided to customer on the order status."],["fa-solid fa-desktop","Responsive Design","Designed to be adaptable to all web platforms."],["fa-solid fa-shield", "Data Security", "Utilizes bcrypt encryption to protect user's password. Paypal API utilized for secure credit card payments or through the Paypal account."],["fa-solid fa-unlock","Administrative tools","Provided access to control menu information."]],
        additionalPic: "../img/enroll-add.png",
        tools: ["MongoDB", "NextJs", "Axios", "Redux", "Paypal API", "Google Maps API"],
        link: "",
        githubLink: "https://github.com/ajaramillo6/enroll2",
    },
]