export const skills = [
    {
        id: 1,
        title: "Front-end web development",
        logo: "skillCard-i fa-brands fa-react",
        desc: "Use React and CSS to create interactive and beautifully designed websites based on stakeholder requirements and needs",
    },
    {
        id: 2,
        title: "Back-end web development",
        logo: "fa-brands fa-node",
        desc: "Use Node-js and MongoDB to store information and create CRUD functionality for the user",
    },
    {
        id: 3,
        title: "Python Automation",
        logo: "skillCard-i fa-brands fa-python",
        desc: "Use Python programming to create executables that automate excel reports and enhance efficiency",
    },
    {
        id: 4,
        title: "MS Office Excel Proficiency",
        logo: "fa-solid fa-chart-line",
        desc: "Created various tools and reports for performance tracking, planning and forecasting. Utilize excel formulas, Pivot tables, vba and more",
    },
]

export const projects = [
    {
        id: 3,
        cat: "Web-development",
        title: "Songproof",
        status: "incomplete",
        img: "./img/songproof.png",
        video: "",
        desc: "Creating a music hosting website which allows registered users to share their own music through posts containing a song and a song cover. Users can subscribe, comment and like. There will be different playlists that songs can be added to. Categories for songs will be shown on the home page. This is a great site to connect with others through music. Dark Mode setting option is available.",
        tools: "MongoDB, Express, React, Node, Axios, Context",
        link: "",
        githubLink: "https://github.com/ajaramillo6",
    },
    {
        id: 2,
        cat: "Web-development",
        title: "Backpack",
        status: "incomplete",
        img: "./img/backpack.png",
        video: "https://drive.google.com/file/d/1lxQXSL0XTLOxkqVipisovul8YdeWQGoj/preview",
        desc: "Created a travel blog website which allows registered users to create their own posts from different trips they’ve been on. Each post can include multiple images and links, making easy for the reader to visualize the location(s) and navigate to related pages via the links provided. If the reader prefers reading with a dark background, the 'Dark Mode' option is available. Unregistered users can subscribe to leave comments and likes on different posts.",
        tools: "MongoDB, Express, React, Node, Axios, Context",
        link: "",
        githubLink: "https://github.com/ajaramillo6/travel",
    },
    {
        id: 1,
        cat: "Web-development",
        title: "Enroll",
        status: "in-process",
        img: "./img/enroll.png",
        video: "https://drive.google.com/file/d/1xtaXzjEC3xMboMd-Thz85Mu8hkQRihhn/preview",
        desc: "This food truck business website allows users to purchase food securely using Paypal. Users can select multiple items from the menu and have additional toppings added. There is an admin page where the website owner can modify the menu as needed by creating new items or deleting obsolete ones. The admin page also allows the selection of ‘Featured’ items to have those be promoted on the home page. Each item containing peanuts or spicy sauce contains an icon for the consumer’s knowledge.",
        tools: "MongoDB, NextJs, React, Node, Axios, Redux, Paypal API, Google Maps API",
        link: "",
        githubLink: "https://github.com/ajaramillo6/enroll2",
    },
]